apps/employees/urls.py
from django.urls import path
from .views import  (
    EmployeesList, 
    EmployeeEdit, 
    EmployeeDelete, 
    EmployeeCreate
)

urlpatterns = [
    path('list', EmployeesList.as_view(), name='list_employees'),
    path('novo/', EmployeeCreate.as_view(), name='create_employee'),
    path('editar/<int:pk>/', EmployeeEdit.as_view(), name='update_employee'),
    path('apagar/<int:pk>/', EmployeeDelete.as_view(), name='delete_employee')
]

gestao_rh/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('apps.core.urls')),
    path('employees/', include('apps.employees.urls')),
    path('departments/', include('apps.departments.urls')),
    path('company/', include('apps.companies.urls')),
    path('document/', include('apps.documents.urls')),
    path('overtimes/', include('apps.overtimes.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/documents/models.py
from django.db import models
from django.shortcuts import reverse

from apps.employees.models import Employee


class Document(models.Model):
    description = models.CharField(max_length=100)
    author = models.ForeignKey(Employee, on_delete=models.PROTECT)
    file = models.FileField(upload_to='documents')

    def get_absolute_url(self):
        return reverse('update_employee', args=[self.author.id])
    
    def __str__(self):
        return self.description

apps/employees/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

from apps.departments.models import Department
from apps.companies.models import Company



class Employee(models.Model):
    name = models.CharField(max_length=100)
    user = models.OneToOneField(User, on_delete=models.PROTECT)
    departments = models.ManyToManyField(Department)
    company = models.ForeignKey(Company, on_delete=models.PROTECT, null=True, blank=True)

    def get_absolute_url(self):
        return reverse('list_employees')
    
    def __str__(self):
        return self.name

apps/employees/views.py
from django.urls import reverse_lazy
from django.contrib.auth.models import User

from django.views.generic import (
    ListView, 
    UpdateView, 
    DeleteView, 
    CreateView
)

from .models import Employee


class EmployeesList(ListView):
    model = Employee

    def get_queryset(self):
        company_logged = self.request.user.employee.company
        return Employee.objects.filter(company=company_logged)

class EmployeeEdit(UpdateView):
    model = Employee
    fields = ['name', 'departments']

class EmployeeDelete(DeleteView):
    model = Employee
    success_url = reverse_lazy('list_employees')

class EmployeeCreate(CreateView):
    model = Employee
    fields = ['name', 'departments']
    
    def form_valid(self, form):
        employee = form.save(commit=False)
        username = employee.name.split(' ')[0] + employee.name.split(' ')[1]
        employee.company = self.request.user.employee.company
        employee.user = User.objects.create(username=username)
        employee.save()
        return super(EmployeeCreate, self).form_valid(form)
        

apps/employees/templates/employees/employee_confirm_delete.html
{% extends 'base.html' %} 
{% block main %}

<form method="POST">
  {% csrf_token %} {{ form }}
    <h1>Você tem certeza que quer apagar {{ object }}</h1>
  <button type="submit" class="btn btn-danger">Confirmar</button>
</form>
{% endblock %}

apps/employees/templates/employees/employee_form.html
{% extends 'base.html' %} 
{% load bootstrap %}
{% block main %} 


<form method="POST">
  {% csrf_token %} {{ form|bootstrap }}

  <button type="submit" class="btn btn-main">Salvar</button>
</form>
<br>

<br>

<br>
<h2>Documentos</h2>
<ul>
{% for document in object.document_set.all %}
    <li>
        <a href="{{ document.arquivo.url }} "> {{ document.description }}  </a><br>
    </li>
{% endfor %}
</ul>

{% if object %}
<a href="{% url 'create_document' object.id %}" class="btn btn-success"> Adicionar documento </a>
{% endif %}

{% for document in object.document_set.all %}
  {{ document }} <br>
{% endfor %}

{% endblock %}

apps/employees/templates/employees/employee_list.html
{% extends 'base.html' %} 
{% block main %} List
<br />
{% for employee in object_list %}
<a href="{% url 'update_employee' employee.id %}">{{ employee }}</a>
<a href="{% url 'delete_employee' employee.id %}">Apagar</a><br />
{% endfor %} 
<a href="{% url 'create_employee' %}" class='btn btn-info'>Novo</a>
{% endblock %}